import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SellCarOptions from "./components/SellCarOptions";
import FeaturedCars from    "./components/FeaturedCars";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-#f8f8f8"
      >
        <Navbar />
        <SellCarOptions/>
        <FeaturedCars/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}
